version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: piketdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  cache:
    image: redis:7
    ports:
      - "6379:6379"
    command: redis-server --requirepass password123

  piketapi:
    build:
      context: .
      dockerfile: PiketWebApi/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:5001
      ASPNETCORE_HTTP_PORTS: "5001"
      ConnectionStrings__piketdb: "Host=db;Port=5432;Username=postgres;Password=password123;Database=piketdb"
      ConnectionStrings__cache: "redis,password=password123"
      JWT_SECRET: "O0ywQA1xv4h1EXL4cnsQ4ReHEoqwMuejtXB4KxOeTCB4nOpV4yVegegbEgtzsZWfl5wlBWBY5kpUPVsEmkVr3V9sxvOPmT4YR3PvUCiw7s1xMrSoCMVqnG7VlSeO469Z"
      JWT_ISSUER: "https://localhost:5001"
      JWT_AUDIENCE: "https://localhost:5001"
      DEFAULT_PASSWORD: "Password@123"
    ports:
      - "5001:5001"
    depends_on:
      - db
      - cache

  admin-client:
    build:
      context: ./smkn8picket-client
      dockerfile: Dockerfile
    environment:
      VITE_API_URL: "http://localhost:5001"
      VITE_LOGO: "/smk.png"
    ports:
      - "8000:80"
    depends_on:
      - piketapi

  whatsapp:
    container_name: whatsapp
    image: 230279/whatsapp:1.0.1
    restart: always
    # build:
    #   context: WhatsApp
    #   dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    depends_on:
      db:
        condition: service_healthy
        restart: true
    ports:
      - 3000:3000

volumes:
  postgres_data:
